name: Generate 3D Profile Contribution

on:
  # 每天运行一次
  schedule:
    - cron: "0 0 * * *"

  # 允许手动触发
  workflow_dispatch:

  # 每次推送到 main 分支时运行
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate 3D github profile

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate 3D Profile
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: yuzhixuanyu34-dotcom

      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "Generated 3D contribution profile" || exit 0
          git push
